export { computeMA, lastN, lastNonNull } from "./ma.js"
export { computeEMA, computeRSI, computeMACD } from "./indicators.js"
export { detectCross, scoreSignal, analyzeSymbol, hasSufficientBars } from "./signal.js"
export { scoreStrongDeath, formatStrongDeathLine, STRONG_DEATH_LABELS, FACTOR_COUNT } from "./strong-death.js"
export { computeStats } from "./stats.js"
export type { OHLCV, ChartData, AssetType } from "./types.js"
export type { SignalType, Confidence, SignalResult } from "./signal.js"
export type { StrongDeathResult, StrongDeathFactors } from "./strong-death.js"
export type { StatsResult, TradeLike, TradeSummary } from "./stats.js"
export type { MACDSeries } from "./indicators.js"
